import type { Destination } from "./types";

export const DESTINATIONS: Destination[] = [
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    blurb: "Hilly, sunny, and affordable, with great seafood and nightlife.",
    budget: "budget",
    tags: ["food", "nightlife", "culture", "history", "beach"],
    activities: ["Tram 28 ride", "Pastel de nata tour", "Day trip to Sintra", "Fado dinner in Alfama"],
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    blurb: "Endless food, neon nightlife, and quiet temples.",
    budget: "mid",
    tags: ["food", "culture", "shopping", "nightlife", "history"],
    activities: ["Tsukiji market breakfast", "Shibuya night walk", "Meiji Shrine", "teamLab digital art"],
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    blurb: "Beaches, rice terraces, yoga retreats, and cheap luxury.",
    budget: "budget",
    tags: ["wellness", "beach", "romantic", "adventure", "culture"],
    activities: ["Sunrise Mount Batur hike", "Ubud rice terrace walk", "Surf lesson in Canggu", "Spa day"],
  },
  {
    id: "banff",
    name: "Banff",
    country: "Canada",
    blurb: "Turquoise lakes, mountain trails, and winter skiing.",
    budget: "mid",
    tags: ["hiking", "skiing", "wildlife", "adventure", "romantic"],
    activities: ["Lake Louise canoe", "Sunshine Village ski day", "Johnston Canyon", "Wildlife drive"],
  },
  {
    id: "cancun",
    name: "Cancun",
    country: "Mexico",
    blurb: "All-inclusive beaches, cenotes, and Mayan ruins nearby.",
    budget: "mid",
    tags: ["beach", "nightlife", "adventure", "history"],
    activities: ["Chichen Itza day trip", "Cenote swim", "Isla Mujeres ferry", "Snorkeling reef tour"],
  },
  {
    id: "paris",
    name: "Paris",
    country: "France",
    blurb: "Art, food, and romance on every corner.",
    budget: "luxury",
    tags: ["culture", "food", "romantic", "history", "shopping"],
    activities: ["Louvre visit", "Seine dinner cruise", "Montmartre walk", "Versailles day trip"],
  },
  {
    id: "reykjavik",
    name: "Reykjavik",
    country: "Iceland",
    blurb: "Waterfalls, geothermal spas, and the northern lights.",
    budget: "luxury",
    tags: ["adventure", "wellness", "hiking", "wildlife", "romantic"],
    activities: ["Blue Lagoon", "Golden Circle drive", "Northern lights tour", "Glacier hike"],
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    blurb: "World-class street food, museums, and markets on a budget.",
    budget: "budget",
    tags: ["food", "culture", "history", "nightlife", "shopping"],
    activities: ["Taco crawl", "Frida Kahlo Museum", "Teotihuacan pyramids", "Xochimilco boats"],
  },
  {
    id: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    blurb: "The adventure capital: bungee, skiing, and epic hiking.",
    budget: "mid",
    tags: ["adventure", "hiking", "skiing", "wildlife", "wellness"],
    activities: ["Bungee jump", "Milford Sound cruise", "Ben Lomond trek", "Wine tasting"],
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    blurb: "Ancient ruins, incredible pasta, and piazzas to linger in.",
    budget: "mid",
    tags: ["history", "food", "culture", "romantic", "shopping"],
    activities: ["Colosseum tour", "Vatican museums", "Trastevere dinner", "Gelato tasting"],
  },
  {
    id: "maui",
    name: "Maui",
    country: "USA",
    blurb: "Beaches, whale watching, and volcano sunrises.",
    budget: "luxury",
    tags: ["beach", "romantic", "wildlife", "hiking", "wellness"],
    activities: ["Road to Hana", "Haleakala sunrise", "Whale watching", "Snorkel Molokini"],
  },
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    blurb: "Street food, temples, and nightlife at bargain prices.",
    budget: "budget",
    tags: ["food", "nightlife", "shopping", "culture", "history"],
    activities: ["Grand Palace", "Floating market", "Street food tour", "Rooftop bar hop"],
  },
  {
    id: "denver",
    name: "Denver",
    country: "USA",
    blurb: "Easy access to Rocky Mountain skiing and hiking, with craft beer.",
    budget: "mid",
    tags: ["skiing", "hiking", "adventure", "nightlife", "food"],
    activities: ["Red Rocks show", "Breckenridge ski day", "Craft brewery crawl", "Rocky Mountain National Park"],
  },
  {
    id: "santorini",
    name: "Santorini",
    country: "Greece",
    blurb: "Whitewashed villages, sunsets, and volcanic beaches.",
    budget: "luxury",
    tags: ["romantic", "beach", "food", "wellness", "history"],
    activities: ["Oia sunset", "Catamaran cruise", "Wine tasting", "Ancient Akrotiri"],
  },
  {
    id: "costa-rica",
    name: "Costa Rica",
    country: "Costa Rica",
    blurb: "Rainforest, wildlife, surf, and zip-lines.",
    budget: "mid",
    tags: ["wildlife", "adventure", "hiking", "beach", "wellness"],
    activities: ["Zip-line canopy tour", "Arenal volcano hike", "Manuel Antonio wildlife", "Surf lesson"],
  },
];
